[project]
name = "promptoptimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-anthropic>=1.7.4",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.12",
    "pandas>=3.0.6",
    "typing-extensions>=4.16.0",
]
