#!/usr/bin/env python3
"""Score responses generated by run_ollama_gemma-2.py."""

from __future__ import annotations

import json
import pathlib
import sys
import argparse

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from score_runs import score_cls, score_id, split_cot  # noqa: E402
import score_markdown as sm  # noqa: E402

DOMAINS = ("library", "car_rental", "ntss")


def relaxed_classification_score(text: str, domain: str) -> dict:
    """Parse headerless four-column pipe rows for diagnostic comparison only."""
    lines = text.splitlines()
    rows = []
    for line in lines:
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != 4:
            continue
        if cells[0].lower() in {"c", "a", "v", "as", "ac", "ag", "i"}:
            rows.append(tuple(cells))
    with __import__("tempfile").NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as fh:
        fh.write("| label | element | arg1 | arg2 |\n|---|---|---|---|\n")
        fh.writelines("| " + " | ".join(row) + " |\n" for row in rows)
        path = pathlib.Path(fh.name)
    try:
        pred = sm.parse_markdown(path)
    finally:
        path.unlink(missing_ok=True)
    gold = sm.parse_csv(ROOT / "ground_truths" / "classification" / f"{domain}.csv")
    pairs = []
    for label in sorted({row[0] for row in gold + pred}):
        pairs.extend(sm.match(
            [row for row in gold if row[0] == label],
            [row for row in pred if row[0] == label],
            True,
            True,
        ))
    tp = len(pairs)
    p = tp / len(pred) if pred else 0
    r = tp / len(gold) if gold else 0
    return {
        "parsed_rows": len(pred),
        "tp": tp,
        "fp": len(pred) - tp,
        "fn": len(gold) - tp,
        "precision": p,
        "recall": r,
        "f1": 2 * p * r / (p + r) if p + r else 0,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="gemma2:latest")
    args = parser.parse_args()
    report = {"mode": "ollama", "model": args.model, "domains": {}}
    for domain in DOMAINS:
        report["domains"][domain] = {}
        id_text = (ROOT / f"responses/identification/P5_gemma-2/{domain}_r1_gemma-2.md").read_text()
        cls_text = (ROOT / f"responses/classification/P4_gemma-2/{domain}_r1_gemma-2.md").read_text()
        cot_text = (ROOT / f"responses/cot/P4_gemma-2/{domain}_r1_gemma-2.md").read_text()
        report["domains"][domain]["identification"] = score_id(id_text, domain)
        report["domains"][domain]["classification"] = score_cls(cls_text, domain)
        report["domains"][domain]["classification_relaxed_diagnostic"] = relaxed_classification_score(
            cls_text, domain
        )
        step1, final = split_cot(cot_text)
        report["domains"][domain]["cot"] = {
            "identification": score_id(step1, domain),
            "classification": score_cls(final, domain) if final else None,
        }
    output = ROOT / "scores/ollama_gemma-2_report.json"
    output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    for domain, scores in report["domains"].items():
        print(
            domain,
            f"id={scores['identification']['f1'] * 100:.1f}",
            f"cls={scores['classification']['f1'] * 100:.1f}",
            f"cot-id={scores['cot']['identification']['f1'] * 100:.1f}",
            f"cot-cls={(scores['cot']['classification'] or {}).get('f1', 0) * 100:.1f}",
        )


if __name__ == "__main__":
    main()
